package com.sc.ymfeed.mybatis.dto;

import java.util.ArrayList;
import java.util.List;

public class ArchivedateExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table b3_solo_archiveDate
     *
     * @mbg.generated Mon Mar 20 18:35:37 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table b3_solo_archiveDate
     *
     * @mbg.generated Mon Mar 20 18:35:37 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table b3_solo_archiveDate
     *
     * @mbg.generated Mon Mar 20 18:35:37 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b3_solo_archiveDate
     *
     * @mbg.generated Mon Mar 20 18:35:37 CST 2017
     */
    public ArchivedateExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b3_solo_archiveDate
     *
     * @mbg.generated Mon Mar 20 18:35:37 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b3_solo_archiveDate
     *
     * @mbg.generated Mon Mar 20 18:35:37 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b3_solo_archiveDate
     *
     * @mbg.generated Mon Mar 20 18:35:37 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b3_solo_archiveDate
     *
     * @mbg.generated Mon Mar 20 18:35:37 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b3_solo_archiveDate
     *
     * @mbg.generated Mon Mar 20 18:35:37 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b3_solo_archiveDate
     *
     * @mbg.generated Mon Mar 20 18:35:37 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b3_solo_archiveDate
     *
     * @mbg.generated Mon Mar 20 18:35:37 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b3_solo_archiveDate
     *
     * @mbg.generated Mon Mar 20 18:35:37 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b3_solo_archiveDate
     *
     * @mbg.generated Mon Mar 20 18:35:37 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b3_solo_archiveDate
     *
     * @mbg.generated Mon Mar 20 18:35:37 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table b3_solo_archiveDate
     *
     * @mbg.generated Mon Mar 20 18:35:37 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOidIsNull() {
            addCriterion("oId is null");
            return (Criteria) this;
        }

        public Criteria andOidIsNotNull() {
            addCriterion("oId is not null");
            return (Criteria) this;
        }

        public Criteria andOidEqualTo(String value) {
            addCriterion("oId =", value, "oid");
            return (Criteria) this;
        }

        public Criteria andOidNotEqualTo(String value) {
            addCriterion("oId <>", value, "oid");
            return (Criteria) this;
        }

        public Criteria andOidGreaterThan(String value) {
            addCriterion("oId >", value, "oid");
            return (Criteria) this;
        }

        public Criteria andOidGreaterThanOrEqualTo(String value) {
            addCriterion("oId >=", value, "oid");
            return (Criteria) this;
        }

        public Criteria andOidLessThan(String value) {
            addCriterion("oId <", value, "oid");
            return (Criteria) this;
        }

        public Criteria andOidLessThanOrEqualTo(String value) {
            addCriterion("oId <=", value, "oid");
            return (Criteria) this;
        }

        public Criteria andOidLike(String value) {
            addCriterion("oId like", value, "oid");
            return (Criteria) this;
        }

        public Criteria andOidNotLike(String value) {
            addCriterion("oId not like", value, "oid");
            return (Criteria) this;
        }

        public Criteria andOidIn(List<String> values) {
            addCriterion("oId in", values, "oid");
            return (Criteria) this;
        }

        public Criteria andOidNotIn(List<String> values) {
            addCriterion("oId not in", values, "oid");
            return (Criteria) this;
        }

        public Criteria andOidBetween(String value1, String value2) {
            addCriterion("oId between", value1, value2, "oid");
            return (Criteria) this;
        }

        public Criteria andOidNotBetween(String value1, String value2) {
            addCriterion("oId not between", value1, value2, "oid");
            return (Criteria) this;
        }

        public Criteria andArchivedatearticlecountIsNull() {
            addCriterion("archiveDateArticleCount is null");
            return (Criteria) this;
        }

        public Criteria andArchivedatearticlecountIsNotNull() {
            addCriterion("archiveDateArticleCount is not null");
            return (Criteria) this;
        }

        public Criteria andArchivedatearticlecountEqualTo(Integer value) {
            addCriterion("archiveDateArticleCount =", value, "archivedatearticlecount");
            return (Criteria) this;
        }

        public Criteria andArchivedatearticlecountNotEqualTo(Integer value) {
            addCriterion("archiveDateArticleCount <>", value, "archivedatearticlecount");
            return (Criteria) this;
        }

        public Criteria andArchivedatearticlecountGreaterThan(Integer value) {
            addCriterion("archiveDateArticleCount >", value, "archivedatearticlecount");
            return (Criteria) this;
        }

        public Criteria andArchivedatearticlecountGreaterThanOrEqualTo(Integer value) {
            addCriterion("archiveDateArticleCount >=", value, "archivedatearticlecount");
            return (Criteria) this;
        }

        public Criteria andArchivedatearticlecountLessThan(Integer value) {
            addCriterion("archiveDateArticleCount <", value, "archivedatearticlecount");
            return (Criteria) this;
        }

        public Criteria andArchivedatearticlecountLessThanOrEqualTo(Integer value) {
            addCriterion("archiveDateArticleCount <=", value, "archivedatearticlecount");
            return (Criteria) this;
        }

        public Criteria andArchivedatearticlecountIn(List<Integer> values) {
            addCriterion("archiveDateArticleCount in", values, "archivedatearticlecount");
            return (Criteria) this;
        }

        public Criteria andArchivedatearticlecountNotIn(List<Integer> values) {
            addCriterion("archiveDateArticleCount not in", values, "archivedatearticlecount");
            return (Criteria) this;
        }

        public Criteria andArchivedatearticlecountBetween(Integer value1, Integer value2) {
            addCriterion("archiveDateArticleCount between", value1, value2, "archivedatearticlecount");
            return (Criteria) this;
        }

        public Criteria andArchivedatearticlecountNotBetween(Integer value1, Integer value2) {
            addCriterion("archiveDateArticleCount not between", value1, value2, "archivedatearticlecount");
            return (Criteria) this;
        }

        public Criteria andArchivedatepublishedarticlecountIsNull() {
            addCriterion("archiveDatePublishedArticleCount is null");
            return (Criteria) this;
        }

        public Criteria andArchivedatepublishedarticlecountIsNotNull() {
            addCriterion("archiveDatePublishedArticleCount is not null");
            return (Criteria) this;
        }

        public Criteria andArchivedatepublishedarticlecountEqualTo(Integer value) {
            addCriterion("archiveDatePublishedArticleCount =", value, "archivedatepublishedarticlecount");
            return (Criteria) this;
        }

        public Criteria andArchivedatepublishedarticlecountNotEqualTo(Integer value) {
            addCriterion("archiveDatePublishedArticleCount <>", value, "archivedatepublishedarticlecount");
            return (Criteria) this;
        }

        public Criteria andArchivedatepublishedarticlecountGreaterThan(Integer value) {
            addCriterion("archiveDatePublishedArticleCount >", value, "archivedatepublishedarticlecount");
            return (Criteria) this;
        }

        public Criteria andArchivedatepublishedarticlecountGreaterThanOrEqualTo(Integer value) {
            addCriterion("archiveDatePublishedArticleCount >=", value, "archivedatepublishedarticlecount");
            return (Criteria) this;
        }

        public Criteria andArchivedatepublishedarticlecountLessThan(Integer value) {
            addCriterion("archiveDatePublishedArticleCount <", value, "archivedatepublishedarticlecount");
            return (Criteria) this;
        }

        public Criteria andArchivedatepublishedarticlecountLessThanOrEqualTo(Integer value) {
            addCriterion("archiveDatePublishedArticleCount <=", value, "archivedatepublishedarticlecount");
            return (Criteria) this;
        }

        public Criteria andArchivedatepublishedarticlecountIn(List<Integer> values) {
            addCriterion("archiveDatePublishedArticleCount in", values, "archivedatepublishedarticlecount");
            return (Criteria) this;
        }

        public Criteria andArchivedatepublishedarticlecountNotIn(List<Integer> values) {
            addCriterion("archiveDatePublishedArticleCount not in", values, "archivedatepublishedarticlecount");
            return (Criteria) this;
        }

        public Criteria andArchivedatepublishedarticlecountBetween(Integer value1, Integer value2) {
            addCriterion("archiveDatePublishedArticleCount between", value1, value2, "archivedatepublishedarticlecount");
            return (Criteria) this;
        }

        public Criteria andArchivedatepublishedarticlecountNotBetween(Integer value1, Integer value2) {
            addCriterion("archiveDatePublishedArticleCount not between", value1, value2, "archivedatepublishedarticlecount");
            return (Criteria) this;
        }

        public Criteria andArchivetimeIsNull() {
            addCriterion("archiveTime is null");
            return (Criteria) this;
        }

        public Criteria andArchivetimeIsNotNull() {
            addCriterion("archiveTime is not null");
            return (Criteria) this;
        }

        public Criteria andArchivetimeEqualTo(Long value) {
            addCriterion("archiveTime =", value, "archivetime");
            return (Criteria) this;
        }

        public Criteria andArchivetimeNotEqualTo(Long value) {
            addCriterion("archiveTime <>", value, "archivetime");
            return (Criteria) this;
        }

        public Criteria andArchivetimeGreaterThan(Long value) {
            addCriterion("archiveTime >", value, "archivetime");
            return (Criteria) this;
        }

        public Criteria andArchivetimeGreaterThanOrEqualTo(Long value) {
            addCriterion("archiveTime >=", value, "archivetime");
            return (Criteria) this;
        }

        public Criteria andArchivetimeLessThan(Long value) {
            addCriterion("archiveTime <", value, "archivetime");
            return (Criteria) this;
        }

        public Criteria andArchivetimeLessThanOrEqualTo(Long value) {
            addCriterion("archiveTime <=", value, "archivetime");
            return (Criteria) this;
        }

        public Criteria andArchivetimeIn(List<Long> values) {
            addCriterion("archiveTime in", values, "archivetime");
            return (Criteria) this;
        }

        public Criteria andArchivetimeNotIn(List<Long> values) {
            addCriterion("archiveTime not in", values, "archivetime");
            return (Criteria) this;
        }

        public Criteria andArchivetimeBetween(Long value1, Long value2) {
            addCriterion("archiveTime between", value1, value2, "archivetime");
            return (Criteria) this;
        }

        public Criteria andArchivetimeNotBetween(Long value1, Long value2) {
            addCriterion("archiveTime not between", value1, value2, "archivetime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table b3_solo_archiveDate
     *
     * @mbg.generated do_not_delete_during_merge Mon Mar 20 18:35:37 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table b3_solo_archiveDate
     *
     * @mbg.generated Mon Mar 20 18:35:37 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}