package com.sc.ymfeed.mybatis.dto;

import com.sc.ymfeed.mybatis.support.BaseObject;

public class Archivedate extends BaseObject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b3_solo_archiveDate.oId
     *
     * @mbg.generated Mon Mar 20 18:35:37 CST 2017
     */
    private String oid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b3_solo_archiveDate.archiveDateArticleCount
     *
     * @mbg.generated Mon Mar 20 18:35:37 CST 2017
     */
    private Integer archivedatearticlecount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b3_solo_archiveDate.archiveDatePublishedArticleCount
     *
     * @mbg.generated Mon Mar 20 18:35:37 CST 2017
     */
    private Integer archivedatepublishedarticlecount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b3_solo_archiveDate.archiveTime
     *
     * @mbg.generated Mon Mar 20 18:35:37 CST 2017
     */
    private Long archivetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b3_solo_archiveDate.oId
     *
     * @return the value of b3_solo_archiveDate.oId
     *
     * @mbg.generated Mon Mar 20 18:35:37 CST 2017
     */
    public String getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b3_solo_archiveDate.oId
     *
     * @param oid the value for b3_solo_archiveDate.oId
     *
     * @mbg.generated Mon Mar 20 18:35:37 CST 2017
     */
    public void setOid(String oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b3_solo_archiveDate.archiveDateArticleCount
     *
     * @return the value of b3_solo_archiveDate.archiveDateArticleCount
     *
     * @mbg.generated Mon Mar 20 18:35:37 CST 2017
     */
    public Integer getArchivedatearticlecount() {
        return archivedatearticlecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b3_solo_archiveDate.archiveDateArticleCount
     *
     * @param archivedatearticlecount the value for b3_solo_archiveDate.archiveDateArticleCount
     *
     * @mbg.generated Mon Mar 20 18:35:37 CST 2017
     */
    public void setArchivedatearticlecount(Integer archivedatearticlecount) {
        this.archivedatearticlecount = archivedatearticlecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b3_solo_archiveDate.archiveDatePublishedArticleCount
     *
     * @return the value of b3_solo_archiveDate.archiveDatePublishedArticleCount
     *
     * @mbg.generated Mon Mar 20 18:35:37 CST 2017
     */
    public Integer getArchivedatepublishedarticlecount() {
        return archivedatepublishedarticlecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b3_solo_archiveDate.archiveDatePublishedArticleCount
     *
     * @param archivedatepublishedarticlecount the value for b3_solo_archiveDate.archiveDatePublishedArticleCount
     *
     * @mbg.generated Mon Mar 20 18:35:37 CST 2017
     */
    public void setArchivedatepublishedarticlecount(Integer archivedatepublishedarticlecount) {
        this.archivedatepublishedarticlecount = archivedatepublishedarticlecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b3_solo_archiveDate.archiveTime
     *
     * @return the value of b3_solo_archiveDate.archiveTime
     *
     * @mbg.generated Mon Mar 20 18:35:37 CST 2017
     */
    public Long getArchivetime() {
        return archivetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b3_solo_archiveDate.archiveTime
     *
     * @param archivetime the value for b3_solo_archiveDate.archiveTime
     *
     * @mbg.generated Mon Mar 20 18:35:37 CST 2017
     */
    public void setArchivetime(Long archivetime) {
        this.archivetime = archivetime;
    }
}