package com.sc.ymfeed.mybatis.dto;

import com.sc.ymfeed.mybatis.support.BaseObject;
import java.util.Date;

public class CommentReply extends BaseObject {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column comment_reply.id
	 *
	 * @mbg.generated Tue Aug 29 13:44:41 CST 2017
	 */
	private String id;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column comment_reply.reply
	 *
	 * @mbg.generated Tue Aug 29 13:44:41 CST 2017
	 */
	private String reply;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column comment_reply.like_count
	 *
	 * @mbg.generated Tue Aug 29 13:44:41 CST 2017
	 */
	private Integer likeCount;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column comment_reply.state
	 *
	 * @mbg.generated Tue Aug 29 13:44:41 CST 2017
	 */
	private Integer state;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column comment_reply.user_account_id
	 *
	 * @mbg.generated Tue Aug 29 13:44:41 CST 2017
	 */
	private String userAccountId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column comment_reply.reply_to_user_account_id
	 *
	 * @mbg.generated Tue Aug 29 13:44:41 CST 2017
	 */
	private String replyToUserAccountId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column comment_reply.feed_info_id
	 *
	 * @mbg.generated Tue Aug 29 13:44:41 CST 2017
	 */
	private String feedInfoId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column comment_reply.feed_comment_id
	 *
	 * @mbg.generated Tue Aug 29 13:44:41 CST 2017
	 */
	private String feedCommentId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column comment_reply.create_time
	 *
	 * @mbg.generated Tue Aug 29 13:44:41 CST 2017
	 */
	private Date createTime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column comment_reply.update_time
	 *
	 * @mbg.generated Tue Aug 29 13:44:41 CST 2017
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column comment_reply.id
	 *
	 * @return the value of comment_reply.id
	 *
	 * @mbg.generated Tue Aug 29 13:44:41 CST 2017
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column comment_reply.id
	 *
	 * @param id
	 *            the value for comment_reply.id
	 *
	 * @mbg.generated Tue Aug 29 13:44:41 CST 2017
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column comment_reply.reply
	 *
	 * @return the value of comment_reply.reply
	 *
	 * @mbg.generated Tue Aug 29 13:44:41 CST 2017
	 */
	public String getReply() {
		return reply;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column comment_reply.reply
	 *
	 * @param reply
	 *            the value for comment_reply.reply
	 *
	 * @mbg.generated Tue Aug 29 13:44:41 CST 2017
	 */
	public void setReply(String reply) {
		this.reply = reply;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column comment_reply.like_count
	 *
	 * @return the value of comment_reply.like_count
	 *
	 * @mbg.generated Tue Aug 29 13:44:41 CST 2017
	 */
	public Integer getLikeCount() {
		return likeCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column comment_reply.like_count
	 *
	 * @param likeCount
	 *            the value for comment_reply.like_count
	 *
	 * @mbg.generated Tue Aug 29 13:44:41 CST 2017
	 */
	public void setLikeCount(Integer likeCount) {
		this.likeCount = likeCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column comment_reply.state
	 *
	 * @return the value of comment_reply.state
	 *
	 * @mbg.generated Tue Aug 29 13:44:41 CST 2017
	 */
	public Integer getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column comment_reply.state
	 *
	 * @param state
	 *            the value for comment_reply.state
	 *
	 * @mbg.generated Tue Aug 29 13:44:41 CST 2017
	 */
	public void setState(Integer state) {
		this.state = state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column comment_reply.user_account_id
	 *
	 * @return the value of comment_reply.user_account_id
	 *
	 * @mbg.generated Tue Aug 29 13:44:41 CST 2017
	 */
	public String getUserAccountId() {
		return userAccountId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column comment_reply.user_account_id
	 *
	 * @param userAccountId
	 *            the value for comment_reply.user_account_id
	 *
	 * @mbg.generated Tue Aug 29 13:44:41 CST 2017
	 */
	public void setUserAccountId(String userAccountId) {
		this.userAccountId = userAccountId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column comment_reply.reply_to_user_account_id
	 *
	 * @return the value of comment_reply.reply_to_user_account_id
	 *
	 * @mbg.generated Tue Aug 29 13:44:41 CST 2017
	 */
	public String getReplyToUserAccountId() {
		return replyToUserAccountId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column comment_reply.reply_to_user_account_id
	 *
	 * @param replyToUserAccountId
	 *            the value for comment_reply.reply_to_user_account_id
	 *
	 * @mbg.generated Tue Aug 29 13:44:41 CST 2017
	 */
	public void setReplyToUserAccountId(String replyToUserAccountId) {
		this.replyToUserAccountId = replyToUserAccountId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column comment_reply.feed_info_id
	 *
	 * @return the value of comment_reply.feed_info_id
	 *
	 * @mbg.generated Tue Aug 29 13:44:41 CST 2017
	 */
	public String getFeedInfoId() {
		return feedInfoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column comment_reply.feed_info_id
	 *
	 * @param feedInfoId
	 *            the value for comment_reply.feed_info_id
	 *
	 * @mbg.generated Tue Aug 29 13:44:41 CST 2017
	 */
	public void setFeedInfoId(String feedInfoId) {
		this.feedInfoId = feedInfoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column comment_reply.feed_comment_id
	 *
	 * @return the value of comment_reply.feed_comment_id
	 *
	 * @mbg.generated Tue Aug 29 13:44:41 CST 2017
	 */
	public String getFeedCommentId() {
		return feedCommentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column comment_reply.feed_comment_id
	 *
	 * @param feedCommentId
	 *            the value for comment_reply.feed_comment_id
	 *
	 * @mbg.generated Tue Aug 29 13:44:41 CST 2017
	 */
	public void setFeedCommentId(String feedCommentId) {
		this.feedCommentId = feedCommentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column comment_reply.create_time
	 *
	 * @return the value of comment_reply.create_time
	 *
	 * @mbg.generated Tue Aug 29 13:44:41 CST 2017
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column comment_reply.create_time
	 *
	 * @param createTime
	 *            the value for comment_reply.create_time
	 *
	 * @mbg.generated Tue Aug 29 13:44:41 CST 2017
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column comment_reply.update_time
	 *
	 * @return the value of comment_reply.update_time
	 *
	 * @mbg.generated Tue Aug 29 13:44:41 CST 2017
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column comment_reply.update_time
	 *
	 * @param updateTime
	 *            the value for comment_reply.update_time
	 *
	 * @mbg.generated Tue Aug 29 13:44:41 CST 2017
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	private String nickname;

	public String getNickname() {
		return nickname;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	private UserAccount userAccount;

	public UserAccount getUserAccount() {
		return userAccount;
	}

	public void setUserAccount(UserAccount userAccount) {
		this.userAccount = userAccount;
	}

}