package com.sc.ymfeed.mybatis.dto;

import com.sc.ymfeed.mybatis.support.BaseObject;
import java.util.Date;

public class Info extends BaseObject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.id
     *
     * @mbg.generated Wed Apr 05 12:59:12 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.title
     *
     * @mbg.generated Wed Apr 05 12:59:12 CST 2017
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.preview_img
     *
     * @mbg.generated Wed Apr 05 12:59:12 CST 2017
     */
    private String previewImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.content
     *
     * @mbg.generated Wed Apr 05 12:59:12 CST 2017
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.author_id
     *
     * @mbg.generated Wed Apr 05 12:59:12 CST 2017
     */
    private Integer authorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.create_time
     *
     * @mbg.generated Wed Apr 05 12:59:12 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.label_id
     *
     * @mbg.generated Wed Apr 05 12:59:12 CST 2017
     */
    private Integer labelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.browse_count
     *
     * @mbg.generated Wed Apr 05 12:59:12 CST 2017
     */
    private Integer browseCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.comment_count
     *
     * @mbg.generated Wed Apr 05 12:59:12 CST 2017
     */
    private Integer commentCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.like_count
     *
     * @mbg.generated Wed Apr 05 12:59:12 CST 2017
     */
    private Integer likeCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.header
     *
     * @mbg.generated Wed Apr 05 12:59:12 CST 2017
     */
    private String header;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.id
     *
     * @return the value of info.id
     *
     * @mbg.generated Wed Apr 05 12:59:12 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.id
     *
     * @param id the value for info.id
     *
     * @mbg.generated Wed Apr 05 12:59:12 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.title
     *
     * @return the value of info.title
     *
     * @mbg.generated Wed Apr 05 12:59:12 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.title
     *
     * @param title the value for info.title
     *
     * @mbg.generated Wed Apr 05 12:59:12 CST 2017
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.preview_img
     *
     * @return the value of info.preview_img
     *
     * @mbg.generated Wed Apr 05 12:59:12 CST 2017
     */
    public String getPreviewImg() {
        return previewImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.preview_img
     *
     * @param previewImg the value for info.preview_img
     *
     * @mbg.generated Wed Apr 05 12:59:12 CST 2017
     */
    public void setPreviewImg(String previewImg) {
        this.previewImg = previewImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.content
     *
     * @return the value of info.content
     *
     * @mbg.generated Wed Apr 05 12:59:12 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.content
     *
     * @param content the value for info.content
     *
     * @mbg.generated Wed Apr 05 12:59:12 CST 2017
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.author_id
     *
     * @return the value of info.author_id
     *
     * @mbg.generated Wed Apr 05 12:59:12 CST 2017
     */
    public Integer getAuthorId() {
        return authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.author_id
     *
     * @param authorId the value for info.author_id
     *
     * @mbg.generated Wed Apr 05 12:59:12 CST 2017
     */
    public void setAuthorId(Integer authorId) {
        this.authorId = authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.create_time
     *
     * @return the value of info.create_time
     *
     * @mbg.generated Wed Apr 05 12:59:12 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.create_time
     *
     * @param createTime the value for info.create_time
     *
     * @mbg.generated Wed Apr 05 12:59:12 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.label_id
     *
     * @return the value of info.label_id
     *
     * @mbg.generated Wed Apr 05 12:59:12 CST 2017
     */
    public Integer getLabelId() {
        return labelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.label_id
     *
     * @param labelId the value for info.label_id
     *
     * @mbg.generated Wed Apr 05 12:59:12 CST 2017
     */
    public void setLabelId(Integer labelId) {
        this.labelId = labelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.browse_count
     *
     * @return the value of info.browse_count
     *
     * @mbg.generated Wed Apr 05 12:59:12 CST 2017
     */
    public Integer getBrowseCount() {
        return browseCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.browse_count
     *
     * @param browseCount the value for info.browse_count
     *
     * @mbg.generated Wed Apr 05 12:59:12 CST 2017
     */
    public void setBrowseCount(Integer browseCount) {
        this.browseCount = browseCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.comment_count
     *
     * @return the value of info.comment_count
     *
     * @mbg.generated Wed Apr 05 12:59:12 CST 2017
     */
    public Integer getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.comment_count
     *
     * @param commentCount the value for info.comment_count
     *
     * @mbg.generated Wed Apr 05 12:59:12 CST 2017
     */
    public void setCommentCount(Integer commentCount) {
        this.commentCount = commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.like_count
     *
     * @return the value of info.like_count
     *
     * @mbg.generated Wed Apr 05 12:59:12 CST 2017
     */
    public Integer getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.like_count
     *
     * @param likeCount the value for info.like_count
     *
     * @mbg.generated Wed Apr 05 12:59:12 CST 2017
     */
    public void setLikeCount(Integer likeCount) {
        this.likeCount = likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.header
     *
     * @return the value of info.header
     *
     * @mbg.generated Wed Apr 05 12:59:12 CST 2017
     */
    public String getHeader() {
        return header;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.header
     *
     * @param header the value for info.header
     *
     * @mbg.generated Wed Apr 05 12:59:12 CST 2017
     */
    public void setHeader(String header) {
        this.header = header;
    }
}