package com.sc.ymfeed.mybatis.dto;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserPersistentExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table user_persistent
	 * @mbg.generated  Mon Jun 12 15:43:03 CST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table user_persistent
	 * @mbg.generated  Mon Jun 12 15:43:03 CST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table user_persistent
	 * @mbg.generated  Mon Jun 12 15:43:03 CST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_persistent
	 * @mbg.generated  Mon Jun 12 15:43:03 CST 2017
	 */
	public UserPersistentExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_persistent
	 * @mbg.generated  Mon Jun 12 15:43:03 CST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_persistent
	 * @mbg.generated  Mon Jun 12 15:43:03 CST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_persistent
	 * @mbg.generated  Mon Jun 12 15:43:03 CST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_persistent
	 * @mbg.generated  Mon Jun 12 15:43:03 CST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_persistent
	 * @mbg.generated  Mon Jun 12 15:43:03 CST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_persistent
	 * @mbg.generated  Mon Jun 12 15:43:03 CST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_persistent
	 * @mbg.generated  Mon Jun 12 15:43:03 CST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_persistent
	 * @mbg.generated  Mon Jun 12 15:43:03 CST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_persistent
	 * @mbg.generated  Mon Jun 12 15:43:03 CST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_persistent
	 * @mbg.generated  Mon Jun 12 15:43:03 CST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table user_persistent
	 * @mbg.generated  Mon Jun 12 15:43:03 CST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("id like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("id not like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andUserAccountIdIsNull() {
			addCriterion("user_account_id is null");
			return (Criteria) this;
		}

		public Criteria andUserAccountIdIsNotNull() {
			addCriterion("user_account_id is not null");
			return (Criteria) this;
		}

		public Criteria andUserAccountIdEqualTo(String value) {
			addCriterion("user_account_id =", value, "userAccountId");
			return (Criteria) this;
		}

		public Criteria andUserAccountIdNotEqualTo(String value) {
			addCriterion("user_account_id <>", value, "userAccountId");
			return (Criteria) this;
		}

		public Criteria andUserAccountIdGreaterThan(String value) {
			addCriterion("user_account_id >", value, "userAccountId");
			return (Criteria) this;
		}

		public Criteria andUserAccountIdGreaterThanOrEqualTo(String value) {
			addCriterion("user_account_id >=", value, "userAccountId");
			return (Criteria) this;
		}

		public Criteria andUserAccountIdLessThan(String value) {
			addCriterion("user_account_id <", value, "userAccountId");
			return (Criteria) this;
		}

		public Criteria andUserAccountIdLessThanOrEqualTo(String value) {
			addCriterion("user_account_id <=", value, "userAccountId");
			return (Criteria) this;
		}

		public Criteria andUserAccountIdLike(String value) {
			addCriterion("user_account_id like", value, "userAccountId");
			return (Criteria) this;
		}

		public Criteria andUserAccountIdNotLike(String value) {
			addCriterion("user_account_id not like", value, "userAccountId");
			return (Criteria) this;
		}

		public Criteria andUserAccountIdIn(List<String> values) {
			addCriterion("user_account_id in", values, "userAccountId");
			return (Criteria) this;
		}

		public Criteria andUserAccountIdNotIn(List<String> values) {
			addCriterion("user_account_id not in", values, "userAccountId");
			return (Criteria) this;
		}

		public Criteria andUserAccountIdBetween(String value1, String value2) {
			addCriterion("user_account_id between", value1, value2, "userAccountId");
			return (Criteria) this;
		}

		public Criteria andUserAccountIdNotBetween(String value1, String value2) {
			addCriterion("user_account_id not between", value1, value2, "userAccountId");
			return (Criteria) this;
		}

		public Criteria andEmailIsNull() {
			addCriterion("email is null");
			return (Criteria) this;
		}

		public Criteria andEmailIsNotNull() {
			addCriterion("email is not null");
			return (Criteria) this;
		}

		public Criteria andEmailEqualTo(String value) {
			addCriterion("email =", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotEqualTo(String value) {
			addCriterion("email <>", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThan(String value) {
			addCriterion("email >", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThanOrEqualTo(String value) {
			addCriterion("email >=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThan(String value) {
			addCriterion("email <", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThanOrEqualTo(String value) {
			addCriterion("email <=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLike(String value) {
			addCriterion("email like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotLike(String value) {
			addCriterion("email not like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailIn(List<String> values) {
			addCriterion("email in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotIn(List<String> values) {
			addCriterion("email not in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailBetween(String value1, String value2) {
			addCriterion("email between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotBetween(String value1, String value2) {
			addCriterion("email not between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andSeriesIsNull() {
			addCriterion("series is null");
			return (Criteria) this;
		}

		public Criteria andSeriesIsNotNull() {
			addCriterion("series is not null");
			return (Criteria) this;
		}

		public Criteria andSeriesEqualTo(String value) {
			addCriterion("series =", value, "series");
			return (Criteria) this;
		}

		public Criteria andSeriesNotEqualTo(String value) {
			addCriterion("series <>", value, "series");
			return (Criteria) this;
		}

		public Criteria andSeriesGreaterThan(String value) {
			addCriterion("series >", value, "series");
			return (Criteria) this;
		}

		public Criteria andSeriesGreaterThanOrEqualTo(String value) {
			addCriterion("series >=", value, "series");
			return (Criteria) this;
		}

		public Criteria andSeriesLessThan(String value) {
			addCriterion("series <", value, "series");
			return (Criteria) this;
		}

		public Criteria andSeriesLessThanOrEqualTo(String value) {
			addCriterion("series <=", value, "series");
			return (Criteria) this;
		}

		public Criteria andSeriesLike(String value) {
			addCriterion("series like", value, "series");
			return (Criteria) this;
		}

		public Criteria andSeriesNotLike(String value) {
			addCriterion("series not like", value, "series");
			return (Criteria) this;
		}

		public Criteria andSeriesIn(List<String> values) {
			addCriterion("series in", values, "series");
			return (Criteria) this;
		}

		public Criteria andSeriesNotIn(List<String> values) {
			addCriterion("series not in", values, "series");
			return (Criteria) this;
		}

		public Criteria andSeriesBetween(String value1, String value2) {
			addCriterion("series between", value1, value2, "series");
			return (Criteria) this;
		}

		public Criteria andSeriesNotBetween(String value1, String value2) {
			addCriterion("series not between", value1, value2, "series");
			return (Criteria) this;
		}

		public Criteria andTokenIsNull() {
			addCriterion("token is null");
			return (Criteria) this;
		}

		public Criteria andTokenIsNotNull() {
			addCriterion("token is not null");
			return (Criteria) this;
		}

		public Criteria andTokenEqualTo(String value) {
			addCriterion("token =", value, "token");
			return (Criteria) this;
		}

		public Criteria andTokenNotEqualTo(String value) {
			addCriterion("token <>", value, "token");
			return (Criteria) this;
		}

		public Criteria andTokenGreaterThan(String value) {
			addCriterion("token >", value, "token");
			return (Criteria) this;
		}

		public Criteria andTokenGreaterThanOrEqualTo(String value) {
			addCriterion("token >=", value, "token");
			return (Criteria) this;
		}

		public Criteria andTokenLessThan(String value) {
			addCriterion("token <", value, "token");
			return (Criteria) this;
		}

		public Criteria andTokenLessThanOrEqualTo(String value) {
			addCriterion("token <=", value, "token");
			return (Criteria) this;
		}

		public Criteria andTokenLike(String value) {
			addCriterion("token like", value, "token");
			return (Criteria) this;
		}

		public Criteria andTokenNotLike(String value) {
			addCriterion("token not like", value, "token");
			return (Criteria) this;
		}

		public Criteria andTokenIn(List<String> values) {
			addCriterion("token in", values, "token");
			return (Criteria) this;
		}

		public Criteria andTokenNotIn(List<String> values) {
			addCriterion("token not in", values, "token");
			return (Criteria) this;
		}

		public Criteria andTokenBetween(String value1, String value2) {
			addCriterion("token between", value1, value2, "token");
			return (Criteria) this;
		}

		public Criteria andTokenNotBetween(String value1, String value2) {
			addCriterion("token not between", value1, value2, "token");
			return (Criteria) this;
		}

		public Criteria andValidTimeIsNull() {
			addCriterion("valid_time is null");
			return (Criteria) this;
		}

		public Criteria andValidTimeIsNotNull() {
			addCriterion("valid_time is not null");
			return (Criteria) this;
		}

		public Criteria andValidTimeEqualTo(Date value) {
			addCriterion("valid_time =", value, "validTime");
			return (Criteria) this;
		}

		public Criteria andValidTimeNotEqualTo(Date value) {
			addCriterion("valid_time <>", value, "validTime");
			return (Criteria) this;
		}

		public Criteria andValidTimeGreaterThan(Date value) {
			addCriterion("valid_time >", value, "validTime");
			return (Criteria) this;
		}

		public Criteria andValidTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("valid_time >=", value, "validTime");
			return (Criteria) this;
		}

		public Criteria andValidTimeLessThan(Date value) {
			addCriterion("valid_time <", value, "validTime");
			return (Criteria) this;
		}

		public Criteria andValidTimeLessThanOrEqualTo(Date value) {
			addCriterion("valid_time <=", value, "validTime");
			return (Criteria) this;
		}

		public Criteria andValidTimeIn(List<Date> values) {
			addCriterion("valid_time in", values, "validTime");
			return (Criteria) this;
		}

		public Criteria andValidTimeNotIn(List<Date> values) {
			addCriterion("valid_time not in", values, "validTime");
			return (Criteria) this;
		}

		public Criteria andValidTimeBetween(Date value1, Date value2) {
			addCriterion("valid_time between", value1, value2, "validTime");
			return (Criteria) this;
		}

		public Criteria andValidTimeNotBetween(Date value1, Date value2) {
			addCriterion("valid_time not between", value1, value2, "validTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("create_time is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("create_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("create_time in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("create_time not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("create_time between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("create_time not between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNull() {
			addCriterion("update_time is null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNotNull() {
			addCriterion("update_time is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeEqualTo(Date value) {
			addCriterion("update_time =", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotEqualTo(Date value) {
			addCriterion("update_time <>", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThan(Date value) {
			addCriterion("update_time >", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("update_time >=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThan(Date value) {
			addCriterion("update_time <", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
			addCriterion("update_time <=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIn(List<Date> values) {
			addCriterion("update_time in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotIn(List<Date> values) {
			addCriterion("update_time not in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeBetween(Date value1, Date value2) {
			addCriterion("update_time between", value1, value2, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
			addCriterion("update_time not between", value1, value2, "updateTime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table user_persistent
	 * @mbg.generated  Mon Jun 12 15:43:03 CST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_persistent
     *
     * @mbg.generated do_not_delete_during_merge Thu Apr 27 12:53:04 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}