package com.sc.ymfeed.mybatis.dto;

import com.sc.ymfeed.mybatis.support.BaseObject;
import java.util.Date;

public class UserAccount extends BaseObject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account.id
     *
     * @mbg.generated Wed Apr 12 16:50:28 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account.email
     *
     * @mbg.generated Wed Apr 12 16:50:28 CST 2017
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account.mobile
     *
     * @mbg.generated Wed Apr 12 16:50:28 CST 2017
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account.password
     *
     * @mbg.generated Wed Apr 12 16:50:28 CST 2017
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account.active
     *
     * @mbg.generated Wed Apr 12 16:50:28 CST 2017
     */
    private Integer active;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account.gag
     *
     * @mbg.generated Wed Apr 12 16:50:28 CST 2017
     */
    private Integer gag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account.blocked
     *
     * @mbg.generated Wed Apr 12 16:50:28 CST 2017
     */
    private Integer blocked;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account.create_time
     *
     * @mbg.generated Wed Apr 12 16:50:28 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account.id
     *
     * @return the value of user_account.id
     *
     * @mbg.generated Wed Apr 12 16:50:28 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account.id
     *
     * @param id the value for user_account.id
     *
     * @mbg.generated Wed Apr 12 16:50:28 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account.email
     *
     * @return the value of user_account.email
     *
     * @mbg.generated Wed Apr 12 16:50:28 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account.email
     *
     * @param email the value for user_account.email
     *
     * @mbg.generated Wed Apr 12 16:50:28 CST 2017
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account.mobile
     *
     * @return the value of user_account.mobile
     *
     * @mbg.generated Wed Apr 12 16:50:28 CST 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account.mobile
     *
     * @param mobile the value for user_account.mobile
     *
     * @mbg.generated Wed Apr 12 16:50:28 CST 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account.password
     *
     * @return the value of user_account.password
     *
     * @mbg.generated Wed Apr 12 16:50:28 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account.password
     *
     * @param password the value for user_account.password
     *
     * @mbg.generated Wed Apr 12 16:50:28 CST 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account.active
     *
     * @return the value of user_account.active
     *
     * @mbg.generated Wed Apr 12 16:50:28 CST 2017
     */
    public Integer getActive() {
        return active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account.active
     *
     * @param active the value for user_account.active
     *
     * @mbg.generated Wed Apr 12 16:50:28 CST 2017
     */
    public void setActive(Integer active) {
        this.active = active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account.gag
     *
     * @return the value of user_account.gag
     *
     * @mbg.generated Wed Apr 12 16:50:28 CST 2017
     */
    public Integer getGag() {
        return gag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account.gag
     *
     * @param gag the value for user_account.gag
     *
     * @mbg.generated Wed Apr 12 16:50:28 CST 2017
     */
    public void setGag(Integer gag) {
        this.gag = gag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account.blocked
     *
     * @return the value of user_account.blocked
     *
     * @mbg.generated Wed Apr 12 16:50:28 CST 2017
     */
    public Integer getBlocked() {
        return blocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account.blocked
     *
     * @param blocked the value for user_account.blocked
     *
     * @mbg.generated Wed Apr 12 16:50:28 CST 2017
     */
    public void setBlocked(Integer blocked) {
        this.blocked = blocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account.create_time
     *
     * @return the value of user_account.create_time
     *
     * @mbg.generated Wed Apr 12 16:50:28 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account.create_time
     *
     * @param createTime the value for user_account.create_time
     *
     * @mbg.generated Wed Apr 12 16:50:28 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}