package com.sc.ymfeed.mybatis.dto;

import com.sc.ymfeed.mybatis.support.BaseObject;
import java.util.Date;

public class UserPersistent extends BaseObject {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_persistent.id
	 * @mbg.generated  Thu Sep 14 23:56:43 CST 2017
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_persistent.user_account_id
	 * @mbg.generated  Thu Sep 14 23:56:43 CST 2017
	 */
	private String userAccountId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_persistent.email
	 * @mbg.generated  Thu Sep 14 23:56:43 CST 2017
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_persistent.series
	 * @mbg.generated  Thu Sep 14 23:56:43 CST 2017
	 */
	private String series;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_persistent.token
	 * @mbg.generated  Thu Sep 14 23:56:43 CST 2017
	 */
	private String token;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_persistent.valid_time
	 * @mbg.generated  Thu Sep 14 23:56:43 CST 2017
	 */
	private Date validTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_persistent.create_time
	 * @mbg.generated  Thu Sep 14 23:56:43 CST 2017
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_persistent.update_time
	 * @mbg.generated  Thu Sep 14 23:56:43 CST 2017
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_persistent.id
	 * @return  the value of user_persistent.id
	 * @mbg.generated  Thu Sep 14 23:56:43 CST 2017
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_persistent.id
	 * @param id  the value for user_persistent.id
	 * @mbg.generated  Thu Sep 14 23:56:43 CST 2017
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_persistent.user_account_id
	 * @return  the value of user_persistent.user_account_id
	 * @mbg.generated  Thu Sep 14 23:56:43 CST 2017
	 */
	public String getUserAccountId() {
		return userAccountId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_persistent.user_account_id
	 * @param userAccountId  the value for user_persistent.user_account_id
	 * @mbg.generated  Thu Sep 14 23:56:43 CST 2017
	 */
	public void setUserAccountId(String userAccountId) {
		this.userAccountId = userAccountId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_persistent.email
	 * @return  the value of user_persistent.email
	 * @mbg.generated  Thu Sep 14 23:56:43 CST 2017
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_persistent.email
	 * @param email  the value for user_persistent.email
	 * @mbg.generated  Thu Sep 14 23:56:43 CST 2017
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_persistent.series
	 * @return  the value of user_persistent.series
	 * @mbg.generated  Thu Sep 14 23:56:43 CST 2017
	 */
	public String getSeries() {
		return series;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_persistent.series
	 * @param series  the value for user_persistent.series
	 * @mbg.generated  Thu Sep 14 23:56:43 CST 2017
	 */
	public void setSeries(String series) {
		this.series = series;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_persistent.token
	 * @return  the value of user_persistent.token
	 * @mbg.generated  Thu Sep 14 23:56:43 CST 2017
	 */
	public String getToken() {
		return token;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_persistent.token
	 * @param token  the value for user_persistent.token
	 * @mbg.generated  Thu Sep 14 23:56:43 CST 2017
	 */
	public void setToken(String token) {
		this.token = token;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_persistent.valid_time
	 * @return  the value of user_persistent.valid_time
	 * @mbg.generated  Thu Sep 14 23:56:43 CST 2017
	 */
	public Date getValidTime() {
		return validTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_persistent.valid_time
	 * @param validTime  the value for user_persistent.valid_time
	 * @mbg.generated  Thu Sep 14 23:56:43 CST 2017
	 */
	public void setValidTime(Date validTime) {
		this.validTime = validTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_persistent.create_time
	 * @return  the value of user_persistent.create_time
	 * @mbg.generated  Thu Sep 14 23:56:43 CST 2017
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_persistent.create_time
	 * @param createTime  the value for user_persistent.create_time
	 * @mbg.generated  Thu Sep 14 23:56:43 CST 2017
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_persistent.update_time
	 * @return  the value of user_persistent.update_time
	 * @mbg.generated  Thu Sep 14 23:56:43 CST 2017
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_persistent.update_time
	 * @param updateTime  the value for user_persistent.update_time
	 * @mbg.generated  Thu Sep 14 23:56:43 CST 2017
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}