package com.sc.ymfeed.mybatis.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.sc.ymfeed.mybatis.dto.CommentReply;

public interface CommentReplyMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table comment_reply
	 *
	 * @mbg.generated Tue Aug 29 13:44:41 CST 2017
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table comment_reply
	 *
	 * @mbg.generated Tue Aug 29 13:44:41 CST 2017
	 */
	int insert(CommentReply record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table comment_reply
	 *
	 * @mbg.generated Tue Aug 29 13:44:41 CST 2017
	 */
	int insertSelective(CommentReply record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table comment_reply
	 *
	 * @mbg.generated Tue Aug 29 13:44:41 CST 2017
	 */
	CommentReply selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table comment_reply
	 *
	 * @mbg.generated Tue Aug 29 13:44:41 CST 2017
	 */
	int updateByPrimaryKeySelective(CommentReply record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table comment_reply
	 *
	 * @mbg.generated Tue Aug 29 13:44:41 CST 2017
	 */
	int updateByPrimaryKey(CommentReply record);

	CommentReply selectCommentReplyById(@Param("commentId") String commentId, @Param("state") int state);

	List<CommentReply> selectCommentReplyByLimit(@Param("commentIds") List<String> commentIds,
			@Param("state") int state, @Param("start") int start, @Param("offset") int offset);
}