package com.sc.ymfeed.mybatis.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.sc.ymfeed.mybatis.dto.CommentReply;

public interface CommentReplyMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table comment_reply
	 * 
	 * @mbg.generated Thu Sep 14 23:56:43 CST 2017
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table comment_reply
	 * 
	 * @mbg.generated Thu Sep 14 23:56:43 CST 2017
	 */
	int insert(CommentReply record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table comment_reply
	 * 
	 * @mbg.generated Thu Sep 14 23:56:43 CST 2017
	 */
	int insertSelective(CommentReply record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table comment_reply
	 * 
	 * @mbg.generated Thu Sep 14 23:56:43 CST 2017
	 */
	CommentReply selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table comment_reply
	 * 
	 * @mbg.generated Thu Sep 14 23:56:43 CST 2017
	 */
	int updateByPrimaryKeySelective(CommentReply record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table comment_reply
	 * 
	 * @mbg.generated Thu Sep 14 23:56:43 CST 2017
	 */
	int updateByPrimaryKey(CommentReply record);

	CommentReply selectCommentReplyById(@Param("replyId") String replyId);

	List<CommentReply> selectCommentReplyByLimit3(@Param("commentIds") List<String> commentIds);

	List<CommentReply> selectCommentReplyByLimit(@Param("commentId") String commentId, @Param("start") int start,
			@Param("offset") int offset);
}