package com.sc.ymfeed.mybatis.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.sc.ymfeed.mybatis.dto.FeedInfo;

public interface FeedInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table feed_info
	 * @mbg.generated  Tue Aug 29 13:44:41 CST 2017
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table feed_info
	 * @mbg.generated  Tue Aug 29 13:44:41 CST 2017
	 */
	int insert(FeedInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table feed_info
	 * @mbg.generated  Tue Aug 29 13:44:41 CST 2017
	 */
	int insertSelective(FeedInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table feed_info
	 * @mbg.generated  Tue Aug 29 13:44:41 CST 2017
	 */
	FeedInfo selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table feed_info
	 * @mbg.generated  Tue Aug 29 13:44:41 CST 2017
	 */
	int updateByPrimaryKeySelective(FeedInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table feed_info
	 * @mbg.generated  Tue Aug 29 13:44:41 CST 2017
	 */
	int updateByPrimaryKey(FeedInfo record);

	List<FeedInfo> selectFeedHomeByLimit(@Param("state") int state, @Param("start") int start,
			@Param("offset") int offset);

}