package com.sc.ymfeed.mybatis.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.sc.ymfeed.mybatis.dto.FeedComment;

public interface FeedCommentMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table feed_comment
	 * 
	 * @mbg.generated Thu Sep 14 23:56:43 CST 2017
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table feed_comment
	 * 
	 * @mbg.generated Thu Sep 14 23:56:43 CST 2017
	 */
	int insert(FeedComment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table feed_comment
	 * 
	 * @mbg.generated Thu Sep 14 23:56:43 CST 2017
	 */
	int insertSelective(FeedComment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table feed_comment
	 * 
	 * @mbg.generated Thu Sep 14 23:56:43 CST 2017
	 */
	FeedComment selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table feed_comment
	 * 
	 * @mbg.generated Thu Sep 14 23:56:43 CST 2017
	 */
	int updateByPrimaryKeySelective(FeedComment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table feed_comment
	 * 
	 * @mbg.generated Thu Sep 14 23:56:43 CST 2017
	 */
	int updateByPrimaryKey(FeedComment record);

	FeedComment selectFeedCommentById(@Param("commentId") String commentId);

	int selectFeedCommentCountById(@Param("feedId") String feedId);

	List<FeedComment> selectFeedCommentByLimit(@Param("feedId") String feedId, @Param("start") int start,
			@Param("offset") int offset);
}