package com.sc.ymfeed.mybatis.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.sc.ymfeed.mybatis.dto.FeedComment;

public interface FeedCommentMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table feed_comment
	 * 
	 * @mbg.generated Tue Aug 29 13:44:41 CST 2017
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table feed_comment
	 * 
	 * @mbg.generated Tue Aug 29 13:44:41 CST 2017
	 */
	int insert(FeedComment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table feed_comment
	 * 
	 * @mbg.generated Tue Aug 29 13:44:41 CST 2017
	 */
	int insertSelective(FeedComment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table feed_comment
	 * 
	 * @mbg.generated Tue Aug 29 13:44:41 CST 2017
	 */
	FeedComment selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table feed_comment
	 * 
	 * @mbg.generated Tue Aug 29 13:44:41 CST 2017
	 */
	int updateByPrimaryKeySelective(FeedComment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table feed_comment
	 * 
	 * @mbg.generated Tue Aug 29 13:44:41 CST 2017
	 */
	int updateByPrimaryKey(FeedComment record);

	List<FeedComment> selectFeedCommentByLimit(@Param("feedId") String feedId, @Param("state") int state,
			@Param("start") int start, @Param("offset") int offset);
}