package com.sc.ymfeed.mybatis.dao;

import com.sc.ymfeed.mybatis.dto.FeedInfo;
import com.sc.ymfeed.mybatis.dto.FeedInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FeedInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed_info
     *
     * @mbg.generated Wed Jul 05 17:35:32 CST 2017
     */
    long countByExample(FeedInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed_info
     *
     * @mbg.generated Wed Jul 05 17:35:32 CST 2017
     */
    int deleteByExample(FeedInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed_info
     *
     * @mbg.generated Wed Jul 05 17:35:32 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed_info
     *
     * @mbg.generated Wed Jul 05 17:35:32 CST 2017
     */
    int insert(FeedInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed_info
     *
     * @mbg.generated Wed Jul 05 17:35:32 CST 2017
     */
    int insertSelective(FeedInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed_info
     *
     * @mbg.generated Wed Jul 05 17:35:32 CST 2017
     */
    List<FeedInfo> selectByExample(FeedInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed_info
     *
     * @mbg.generated Wed Jul 05 17:35:32 CST 2017
     */
    FeedInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed_info
     *
     * @mbg.generated Wed Jul 05 17:35:32 CST 2017
     */
    int updateByExampleSelective(@Param("record") FeedInfo record, @Param("example") FeedInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed_info
     *
     * @mbg.generated Wed Jul 05 17:35:32 CST 2017
     */
    int updateByExample(@Param("record") FeedInfo record, @Param("example") FeedInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed_info
     *
     * @mbg.generated Wed Jul 05 17:35:32 CST 2017
     */
    int updateByPrimaryKeySelective(FeedInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed_info
     *
     * @mbg.generated Wed Jul 05 17:35:32 CST 2017
     */
    int updateByPrimaryKey(FeedInfo record);
}