package com.sc.ymfeed.mybatis.dao;

import com.sc.ymfeed.mybatis.dto.UserAccount;
import com.sc.ymfeed.mybatis.dto.UserAccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserAccountMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_account
	 * @mbg.generated  Mon Jun 12 15:43:03 CST 2017
	 */
	long countByExample(UserAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_account
	 * @mbg.generated  Mon Jun 12 15:43:03 CST 2017
	 */
	int deleteByExample(UserAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_account
	 * @mbg.generated  Mon Jun 12 15:43:03 CST 2017
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_account
	 * @mbg.generated  Mon Jun 12 15:43:03 CST 2017
	 */
	int insert(UserAccount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_account
	 * @mbg.generated  Mon Jun 12 15:43:03 CST 2017
	 */
	int insertSelective(UserAccount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_account
	 * @mbg.generated  Mon Jun 12 15:43:03 CST 2017
	 */
	List<UserAccount> selectByExample(UserAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_account
	 * @mbg.generated  Mon Jun 12 15:43:03 CST 2017
	 */
	UserAccount selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_account
	 * @mbg.generated  Mon Jun 12 15:43:03 CST 2017
	 */
	int updateByExampleSelective(@Param("record") UserAccount record, @Param("example") UserAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_account
	 * @mbg.generated  Mon Jun 12 15:43:03 CST 2017
	 */
	int updateByExample(@Param("record") UserAccount record, @Param("example") UserAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_account
	 * @mbg.generated  Mon Jun 12 15:43:03 CST 2017
	 */
	int updateByPrimaryKeySelective(UserAccount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_account
	 * @mbg.generated  Mon Jun 12 15:43:03 CST 2017
	 */
	int updateByPrimaryKey(UserAccount record);
}