package com.sc.ymfeed.mybatis.dao;

import com.sc.ymfeed.mybatis.dto.UserPersistent;
import com.sc.ymfeed.mybatis.dto.UserPersistentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserPersistentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_persistent
     *
     * @mbg.generated Wed Jul 05 17:35:32 CST 2017
     */
    long countByExample(UserPersistentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_persistent
     *
     * @mbg.generated Wed Jul 05 17:35:32 CST 2017
     */
    int deleteByExample(UserPersistentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_persistent
     *
     * @mbg.generated Wed Jul 05 17:35:32 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_persistent
     *
     * @mbg.generated Wed Jul 05 17:35:32 CST 2017
     */
    int insert(UserPersistent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_persistent
     *
     * @mbg.generated Wed Jul 05 17:35:32 CST 2017
     */
    int insertSelective(UserPersistent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_persistent
     *
     * @mbg.generated Wed Jul 05 17:35:32 CST 2017
     */
    List<UserPersistent> selectByExample(UserPersistentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_persistent
     *
     * @mbg.generated Wed Jul 05 17:35:32 CST 2017
     */
    UserPersistent selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_persistent
     *
     * @mbg.generated Wed Jul 05 17:35:32 CST 2017
     */
    int updateByExampleSelective(@Param("record") UserPersistent record, @Param("example") UserPersistentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_persistent
     *
     * @mbg.generated Wed Jul 05 17:35:32 CST 2017
     */
    int updateByExample(@Param("record") UserPersistent record, @Param("example") UserPersistentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_persistent
     *
     * @mbg.generated Wed Jul 05 17:35:32 CST 2017
     */
    int updateByPrimaryKeySelective(UserPersistent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_persistent
     *
     * @mbg.generated Wed Jul 05 17:35:32 CST 2017
     */
    int updateByPrimaryKey(UserPersistent record);
}