package com.sc.ymfeed.mybatis.dao;

import com.sc.ymfeed.mybatis.dto.UserInfo;

public interface UserInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_info
	 * @mbg.generated  Mon Jul 17 18:29:46 CST 2017
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_info
	 * @mbg.generated  Mon Jul 17 18:29:46 CST 2017
	 */
	int insert(UserInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_info
	 * @mbg.generated  Mon Jul 17 18:29:46 CST 2017
	 */
	int insertSelective(UserInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_info
	 * @mbg.generated  Mon Jul 17 18:29:46 CST 2017
	 */
	UserInfo selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_info
	 * @mbg.generated  Mon Jul 17 18:29:46 CST 2017
	 */
	int updateByPrimaryKeySelective(UserInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_info
	 * @mbg.generated  Mon Jul 17 18:29:46 CST 2017
	 */
	int updateByPrimaryKey(UserInfo record);
}