package com.sc.ymfeed.mybatis.dao;

import org.apache.ibatis.annotations.Param;

import com.sc.ymfeed.mybatis.dto.UserAccount;

public interface UserAccountMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_account
	 * @mbg.generated  Tue Jul 18 16:55:12 CST 2017
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_account
	 * @mbg.generated  Tue Jul 18 16:55:12 CST 2017
	 */
	int insert(UserAccount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_account
	 * @mbg.generated  Tue Jul 18 16:55:12 CST 2017
	 */
	int insertSelective(UserAccount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_account
	 * @mbg.generated  Tue Jul 18 16:55:12 CST 2017
	 */
	UserAccount selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_account
	 * @mbg.generated  Tue Jul 18 16:55:12 CST 2017
	 */
	int updateByPrimaryKeySelective(UserAccount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_account
	 * @mbg.generated  Tue Jul 18 16:55:12 CST 2017
	 */
	int updateByPrimaryKey(UserAccount record);

	UserAccount selectByEmail(@Param("email") String email);

	UserAccount selectByNickname(@Param("nickname") String nickname);

	UserAccount selectByActiveCodeAndActive(@Param("activeCode") String activeCode, @Param("active") boolean active);
}