package com.sc.ymfeed.mybatis.dao;

import org.apache.ibatis.annotations.Param;

import com.sc.ymfeed.mybatis.dto.UserPersistent;

public interface UserPersistentMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_persistent
	 * @mbg.generated  Tue Aug 29 13:44:41 CST 2017
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_persistent
	 * @mbg.generated  Tue Aug 29 13:44:41 CST 2017
	 */
	int insert(UserPersistent record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_persistent
	 * @mbg.generated  Tue Aug 29 13:44:41 CST 2017
	 */
	int insertSelective(UserPersistent record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_persistent
	 * @mbg.generated  Tue Aug 29 13:44:41 CST 2017
	 */
	UserPersistent selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_persistent
	 * @mbg.generated  Tue Aug 29 13:44:41 CST 2017
	 */
	int updateByPrimaryKeySelective(UserPersistent record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_persistent
	 * @mbg.generated  Tue Aug 29 13:44:41 CST 2017
	 */
	int updateByPrimaryKey(UserPersistent record);

	UserPersistent selectByUserAccountId(@Param("userAccountId") String userAccountId);
	
	UserPersistent selectByEmailAndSeries(@Param("email") String email, @Param("series") String series);
	
	int deleteByUserAccountId(@Param("userAccountId") String userAccountId);
}